//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DronPageEntities : DbContext
    {
        public DronPageEntities()
            : base("name=DronPageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatMotivoCorreo> CatMotivoCorreos { get; set; }
        public virtual DbSet<CatServicio> CatServicios { get; set; }
        public virtual DbSet<CatPregunta> CatPreguntas { get; set; }
        public virtual DbSet<FechasReservada> FechasReservadas { get; set; }
        public virtual DbSet<FormularioContacto> FormularioContactoes { get; set; }
    
        public virtual int CatMotivoCorreoAdd(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatMotivoCorreoAdd", descripcionParameter);
        }
    
        public virtual int CatMotivoCorreoDelete(Nullable<int> idMotivoCorreo)
        {
            var idMotivoCorreoParameter = idMotivoCorreo.HasValue ?
                new ObjectParameter("IdMotivoCorreo", idMotivoCorreo) :
                new ObjectParameter("IdMotivoCorreo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatMotivoCorreoDelete", idMotivoCorreoParameter);
        }
    
        public virtual ObjectResult<CatMotivoCorreoGetAll_Result> CatMotivoCorreoGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatMotivoCorreoGetAll_Result>("CatMotivoCorreoGetAll");
        }
    
        public virtual ObjectResult<CatMotivoCorreoGetById_Result> CatMotivoCorreoGetById(Nullable<int> idMotivoCorreo)
        {
            var idMotivoCorreoParameter = idMotivoCorreo.HasValue ?
                new ObjectParameter("IdMotivoCorreo", idMotivoCorreo) :
                new ObjectParameter("IdMotivoCorreo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatMotivoCorreoGetById_Result>("CatMotivoCorreoGetById", idMotivoCorreoParameter);
        }
    
        public virtual int CatMotivoCorreoUpdate(Nullable<int> idMotivoCorreo, string descripcion)
        {
            var idMotivoCorreoParameter = idMotivoCorreo.HasValue ?
                new ObjectParameter("IdMotivoCorreo", idMotivoCorreo) :
                new ObjectParameter("IdMotivoCorreo", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatMotivoCorreoUpdate", idMotivoCorreoParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<CatServicioGetAll_Result> CatServicioGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatServicioGetAll_Result>("CatServicioGetAll");
        }
    
        public virtual ObjectResult<CatPreguntaGetAll_Result> CatPreguntaGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPreguntaGetAll_Result>("CatPreguntaGetAll");
        }
    
        public virtual int FormularioContactoAdd(string nombreUsuario, string emailUsuario, string telefono, string cantidadDrones, string fecha, Nullable<int> idCatServicio, string ciudad)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            var emailUsuarioParameter = emailUsuario != null ?
                new ObjectParameter("EmailUsuario", emailUsuario) :
                new ObjectParameter("EmailUsuario", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var cantidadDronesParameter = cantidadDrones != null ?
                new ObjectParameter("CantidadDrones", cantidadDrones) :
                new ObjectParameter("CantidadDrones", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(string));
    
            var idCatServicioParameter = idCatServicio.HasValue ?
                new ObjectParameter("IdCatServicio", idCatServicio) :
                new ObjectParameter("IdCatServicio", typeof(int));
    
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("Ciudad", ciudad) :
                new ObjectParameter("Ciudad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FormularioContactoAdd", nombreUsuarioParameter, emailUsuarioParameter, telefonoParameter, cantidadDronesParameter, fechaParameter, idCatServicioParameter, ciudadParameter);
        }
    }
}
